name: LobbySystem
version: '${project.version}'
main: com.eyenet.lobbysystem.Main
api-version: 1.19
authors: [ BambergNoa, BrandLaurent ]
description: Lobby System
commands:
  ping:
    description: "Ping command"
  wild:
    description: "Teleport to random location"
    aliases:
      - rtp
      - randomtp
  checkdb:
    description: "Check database"
  balance:
    description: "Check balance"
    aliases:
      - bal
  transfer:
    description: "Transfer money"
    aliases:
      - pay
  report:
    description: "Report a player"
    aliases:
      - reportplayer